import time
import pyodbc
import subprocess
import requests

# --- Configuration ---
# The URL generated by your Azure Automation Webhook
WEBHOOK_URL = ""
STOP_WEBHOOK_URL = ""

# Synapse SQL Configuration
SYNAPSE_SERVER = "" # YOUR_WORKSPACE_NAME-ondemand.sql.azuresynapse.net
DATABASE = "" # YOUR_DATABASE_NAME
SQL_USER = "" # YOUR_SQL_USERNAME
SQL_PASS = "" # YOUR_SQL_PASSWORD

def start_vm_via_webhook():
    print("Pinging Azure Webhook to start the Virtual Machine...")
    
    # A simple HTTP POST request triggers the Azure Runbook to turn on the VM
    response = requests.post(WEBHOOK_URL)
    
    # Azure Webhooks return a 202 Accepted status code if successful
    if response.status_code == 202:
        print("Webhook accepted - Azure is booting the VM in the background.")
    else:
        print(f"Webhook failed with status code: {response.status_code}")
        print(f"Response: {response.text}")

def stop_vm_via_webhook():
    print("Pinging Azure Webhook to deallocate the Virtual Machine...")
    response = requests.post(STOP_WEBHOOK_URL)
    
    if response.status_code == 202:
        print("Webhook accepted! Azure is powering down the VM to save costs.")
    else:
        print(f"Webhook failed with status code: {response.status_code}")

def query_synapse():
    print("Connecting to Azure Synapse Serverless SQL...")
    conn_str = (
        "Driver={ODBC Driver 17 for SQL Server};"
        f"Server=tcp:{SYNAPSE_SERVER},1433;"
        f"Database={DATABASE};"
        f"Uid={SQL_USER};"
        f"Pwd={SQL_PASS};"
        "Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
    )
    
    try:
        conn = pyodbc.connect(conn_str)
        cursor = conn.cursor()
        
        print("Executing query against vw_NetworkTraffic...")
        cursor.execute("SELECT TOP 10 * FROM vw_NetworkTraffic ORDER BY EventTime DESC")
        
        rows = cursor.fetchall()
        print(f"Query successful. Retrieved {len(rows)} latest records:\n")
        for row in rows:
            print(row)
            
        conn.close()
    except Exception as e:
        print(f"SQL Error: {e}")

if __name__ == "__main__":
    # Trigger the VM to turn on
    start_vm_via_webhook()
    
    # Wait 60 seconds to ensure the VM is fully booted and the network interface is up
    print("Waiting 60 seconds for VM network interface to initialize...")
    time.sleep(60)
    
    # Launch simulator script
    print("Launching Network Simulator...")
    try:
        # Runs the simulator for 60 seconds then stops it automatically
        subprocess.run(["python", "network_ping_script.py"], timeout=60)
    except subprocess.TimeoutExpired:
        print("Simulator finished its 60-second run.")

    # Wait for Azure to dump the flow logs
    print("Waiting 100 seconds for Azure to batch flow logs to the Storage Account...")
    time.sleep(100) 
    
    # Read data
    query_synapse()
    
    # Tear down infrastructure
    stop_vm_via_webhook()
    
    print("Automation pipeline complete!")